#Valores de referencia
insert into MH_VALORES_REFERENCIA (SAT_OXIGENO_MIN,SAT_OXIGENO_MAX,TEMPERATURA_MIN,TEMPERATURA_MAX,CAPNOGRAFIA_MIN,CAPNOGRAFIA_MAX,
FREC_CARDIACA_MIN,FREC_CARDIACA_MAX,FREC_RESPIRATORIA_MIN,FREC_RESPIRATORIA_MAX,ID_VALREF,PRE_ART_SISTOLICA_MIN,PRE_ART_SISTOLICA_MAX,PRE_ART_DIASTOLICA_MIN,PRE_ART_DIASTOLICA_MAX)
values(95.0,100.0,34.2,40.0,123,123,60,100,12,18,1,90,120,60,80);

commit;