truncate mh_medidas;
truncate mh_valores_referencia;
 
#Pacientes
INSERT INTO MH_MEDIDAS (FECHA_MEDICION,SATURACION_OXIGENO,TEMPERATURA,FREC_CARDIACA,FREC_RESPIRATORIA,ID_PACIENTE,ID_CARETA,ALERTA,PRE_ART_SISTOLICA,PRE_ART_DIASTOLICA)
VALUES(now(),92.4,34.5,75,10,1,(select ID_CARETA from mh_paciente where ID_PACIENTE=1),1,120,70);

INSERT INTO MH_MEDIDAS (FECHA_MEDICION,SATURACION_OXIGENO,TEMPERATURA,FREC_CARDIACA,FREC_RESPIRATORIA,ID_PACIENTE,ID_CARETA,ALERTA,PRE_ART_SISTOLICA,PRE_ART_DIASTOLICA)
VALUES(now(),97.4,41.5,55,13,2,(select ID_CARETA from mh_paciente where ID_PACIENTE=2),1,180,80);

#Valores de referencia
insert into mh_valores_referencia (SAT_OXIGENO_MIN,SAT_OXIGENO_MAX,TEMPERATURA_MIN,TEMPERATURA_MAX,CAPNOGRAFIA_MIN,CAPNOGRAFIA_MAX,
FREC_CARDIACA_MIN,FREC_CARDIACA_MAX,FREC_RESPIRATORIA_MIN,FREC_RESPIRATORIA_MAX,ID_VALREF,PRE_ART_SISTOLICA_MIN,PRE_ART_SISTOLICA_MAX,PRE_ART_DIASTOLICA_MIN,PRE_ART_DIASTOLICA_MAX)
values(95.0,100.0,34.2,40.0,123,123,60,100,12,18,1,90,120,60,80);