/* ------------------------------------------------------------------------ */
/*  Base de datos para el Sistema de Monitoreo del Estado de Salud de       */
/*  Pacientes COVID-19 en Hospitales                                        */
/*  Autor: Iliac Huerta Trujillo			      		    */
/*  Creado : 28-Sep-2020 04:15:34 p.m. 				    	    */
/*  DBMS   : MySql 							    */
/* ------------------------------------------------------------------------ */
/*create database sismhosp;*/

use sismhosp;

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `MH_ANTECEDENTES` CASCADE
;

DROP TABLE IF EXISTS `MH_BITACORA` CASCADE
;

DROP TABLE IF EXISTS `MH_CARETA` CASCADE
;

DROP TABLE IF EXISTS `MH_CARETA_HOSPITAL` CASCADE
;

DROP TABLE IF EXISTS `MH_ESTADOPACIENTE` CASCADE
;

DROP TABLE IF EXISTS `MH_EVENTOBITACORA` CASCADE
;

DROP TABLE IF EXISTS `MH_GENERO` CASCADE
;

DROP TABLE IF EXISTS `MH_HOSPITAL_MEDICO` CASCADE
;

DROP TABLE IF EXISTS `MH_HOSPITAL` CASCADE
;

DROP TABLE IF EXISTS `MH_MEDICO` CASCADE
;

DROP TABLE IF EXISTS `MH_MEDIDAS` CASCADE
;

DROP TABLE IF EXISTS `MH_MENU` CASCADE
;

DROP TABLE IF EXISTS `MH_MENU_OPCION` CASCADE
;

DROP TABLE IF EXISTS `MH_OPCION` CASCADE
;

DROP TABLE IF EXISTS `MH_PACIENTE` CASCADE
;

DROP TABLE IF EXISTS `MH_PACIENTE_MEDICO` CASCADE
;

DROP TABLE IF EXISTS `MH_PERSONA` CASCADE
;

DROP TABLE IF EXISTS `MH_ROL` CASCADE
;

DROP TABLE IF EXISTS `MH_ROL_MENU` CASCADE
;

DROP TABLE IF EXISTS `MH_SINTOMAS` CASCADE
;

DROP TABLE IF EXISTS `MH_USUARIO` CASCADE
;

DROP TABLE IF EXISTS `MH_USUARIO_ROL` CASCADE
;

DROP TABLE IF EXISTS `MH_VALORES_REFERENCIA` CASCADE
;

/* Create Tables */

CREATE TABLE `MH_ANTECEDENTES`
(
	`DIABETES` BOOL NULL,
	`CANCER` BOOL NULL,
	`ID_PACIENTE` BIGINT NOT NULL,
	`ASMA` BOOL NULL,
	`VIH` BOOL NULL,
	`HAS` BOOL NULL,
	`EPOC` BOOL NULL,
	`EMBARAZO` BOOL NULL,
	`ARTRITIS` BOOL NULL,
	`ENFAUTOINMUNE` BOOL NULL,
	`FECHA` DATE NOT NULL,
	CONSTRAINT `PK_MH_ANTECEDENTES` PRIMARY KEY (`ID_PACIENTE` ASC)
)
COMMENT = '

Sistema de Monitoreo del Estado de Salud de Pacientes COVID-19 en Hospitales'

;

CREATE TABLE `MH_BITACORA`
(
	`ID_ENTRADA` BIGINT NOT NULL AUTO_INCREMENT,
	`FECHA_ENTRADA` DATE NULL,
	`ID_EVENTO` INT NULL,
	`ID_USUARIO` VARCHAR(20) NULL,
	CONSTRAINT `PK_MH_BITACORA` PRIMARY KEY (`ID_ENTRADA` ASC)
)

;

CREATE TABLE `MH_CARETA`
(
	`ID_CARETA` BIGINT NOT NULL AUTO_INCREMENT,
    `NO_SERIE` BIGINT NOT NULL,
	`FECHA_MANUFACTURA` DATETIME NOT NULL,
	CONSTRAINT `PK_CARETA` PRIMARY KEY (`ID_CARETA` ASC)
)

;

CREATE TABLE `MH_CARETA_HOSPITAL`
(
	`FECHA_ASIGNACION` VARCHAR(50) NOT NULL,
	`ID_CARETA` BIGINT NOT NULL,
	`ID_HOSPITAL` INT NOT NULL,
	CONSTRAINT `PK_MH_CARETA_HOSPITAL` PRIMARY KEY (`ID_CARETA` ASC, `ID_HOSPITAL` ASC)
)

;

CREATE TABLE `MH_ESTADOPACIENTE`
(
	`ID_ESTADOPACIENTE` SMALLINT NOT NULL,
	`DESCRIPCION` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_MH_ESTADOPACIENTE` PRIMARY KEY (`ID_ESTADOPACIENTE` ASC)
)

;

CREATE TABLE `MH_EVENTOBITACORA`
(
	`ID_EVENTO` INT NOT NULL,
	`DESCRIPCION` VARCHAR(50) NULL,
	CONSTRAINT `PK_MH_EVENTOBITACORA` PRIMARY KEY (`ID_EVENTO` ASC)
)

;

CREATE TABLE `MH_GENERO`
(
	`ID_GENERO` SMALLINT NOT NULL,
	`DESCRIPCION` VARCHAR(30) NULL,
	CONSTRAINT `PK_MH_GENERO` PRIMARY KEY (`ID_GENERO` ASC)
)
COMMENT = 'Tabla de generos asociados a las personas.'

;

CREATE TABLE `MH_HOSPITAL_MEDICO`
(
	`ID_HOSPITAL` INT NOT NULL,
	`ID_MEDICO` INT NOT NULL,
	CONSTRAINT `PK_MH_HOSPITAL_MEDICO` PRIMARY KEY (`ID_HOSPITAL` ASC, `ID_MEDICO` ASC)
)
COMMENT = 'Tabla de relación medicos con hospitales. 

un médico puede estar en varios hospitales.'

;

CREATE TABLE `MH_HOSPITAL`
(
	`ID_HOSPITAL` INT NOT NULL AUTO_INCREMENT,
	`NOMBRE` VARCHAR(50) NOT NULL,
	`UBICACION_GEO` VARCHAR(50) NOT NULL,
	`TEL_EMERGENCIAS` VARCHAR(50) NULL,
	`DIR_CALLE` VARCHAR(50) NULL,
	`NUMERO` INT NULL,
	`COLONIA` VARCHAR(50) NULL,
	`MUNICIPIO` VARCHAR(50) NULL,
	`ESTADO` VARCHAR(50) NULL,
	CONSTRAINT `PK_HOSPITAL` PRIMARY KEY (`ID_HOSPITAL` ASC)
)
COMMENT = 'Entidad para representar hospitales en los cuales se asocianpacientes y doctores.'

;

CREATE TABLE `MH_MEDICO`
(
	`ID_MEDICO` INT NOT NULL AUTO_INCREMENT,
	`CEDULA_PROF` VARCHAR(10) NOT NULL,
	`ID_PERSONA` INT NOT NULL,
	`CELULAR` VARCHAR(12) NOT NULL,
	CONSTRAINT `PK_MEDICO` PRIMARY KEY (`ID_MEDICO` ASC)
)
COMMENT = 'Tabla de medicos que pertenecen a un hospital.

Un médico puede estar asociado a más de un hospital. 

Supongo que el administrador se encargará de llevar a cabo esa relación.'

;

CREATE TABLE `MH_MEDIDAS`
(
	`FECHA_MEDICION` DATETIME NOT NULL,
	`SATURACION_OXIGENO` FLOAT(5,2) NOT NULL,
	`TEMPERATURA` FLOAT(4,2) NOT NULL,
	`FREC_CARDIACA` SMALLINT NOT NULL,
	`FREC_RESPIRATORIA` SMALLINT NOT NULL,
	`ID_PACIENTE` BIGINT NOT NULL,
	`ID_CARETA` BIGINT NOT NULL,
	`ID_MEDICION` BIGINT NOT NULL AUTO_INCREMENT,
	`ALERTA` BOOL NOT NULL DEFAULT FALSE,
	`PRE_ART_SISTOLICA` INT NOT NULL,
	`PRE_ART_DIASTOLICA` INT NOT NULL,
	CONSTRAINT `PK_MH_MEDIDAS` PRIMARY KEY (`ID_MEDICION` ASC, `ID_CARETA` ASC, `ID_PACIENTE` ASC)
)

;

CREATE TABLE `MH_MENU`
(
	`ID_MENU` SMALLINT NOT NULL,
	`DESCRIPCION` VARCHAR(50) NULL,
	`RUTA_ICONO` VARCHAR(100) NULL,
	`POSICION` SMALLINT NULL,
	CONSTRAINT `PK_MH_MENU` PRIMARY KEY (`ID_MENU` ASC)
)
COMMENT = 'Tabla propuesta para generar los menús de forma dinámica'

;

CREATE TABLE `MH_MENU_OPCION`
(
	`ID_MENU_OPCION` INT NOT NULL,
	`ID_MENU` SMALLINT NOT NULL,
	`ID_OPCION` INT NOT NULL,
	`ID_SUB_MENU` SMALLINT NULL,
	`POSICION` SMALLINT NULL,
	CONSTRAINT `PK_MH_MENU_OPCION` PRIMARY KEY (`ID_MENU_OPCION` ASC)
)
COMMENT = 'Tabla que relaciona las opciones que van a conformar a cada menu.'

;

CREATE TABLE `MH_OPCION`
(
	`ID_OPCION` INT NOT NULL,
	`DESCRIPCION` VARCHAR(50) NULL,
	`RUTA_ICONO` VARCHAR(50) NULL,
	`ACCION` VARCHAR(100) NULL,
	CONSTRAINT `PK_MH_OPCION` PRIMARY KEY (`ID_OPCION` ASC)
)
COMMENT = 'Tabla propuesta para la definición de opciones con los que se conformarán los diferentes menús y submenús.'

;

CREATE TABLE `MH_PACIENTE`
(
	`ID_PACIENTE` BIGINT NOT NULL AUTO_INCREMENT,
	`ID_PERSONA` INT NULL,
	`DIR_CALLE` VARCHAR(50) NULL,
	`ID_HOSPITAL` INT NULL,
	`DIR_NUMERO` INT NULL,
	`DIR_INTERIOR` VARCHAR(50) NULL,
	`TEL_FIJO` VARCHAR(12) NULL,
	`TEL_CEL` VARCHAR(12) NULL,
	`ID_CARETA` BIGINT NULL,
	`ID_ESTADOPACIENTE` SMALLINT NULL,
	CONSTRAINT `PK_PACIENTE` PRIMARY KEY (`ID_PACIENTE` ASC)
)
COMMENT = 'Tabla para almacenar los datos generales de un Paciente, se asocia con persona, Hospital y Doctor'

;

CREATE TABLE `MH_PACIENTE_MEDICO`
(
	`FECHA_INICIO` DATETIME NULL,
	`ID_PACIENTE` BIGINT NOT NULL,
	`ID_MEDICO` INT NOT NULL,
	CONSTRAINT `PK_MH_PACIENTE_MEDICO` PRIMARY KEY (`ID_PACIENTE` ASC, `ID_MEDICO` ASC)
)

;

CREATE TABLE `MH_PERSONA`
(
	`ID_PERSONA` INT NOT NULL AUTO_INCREMENT,
	`ID_GENERO` SMALLINT NULL,
	`NOMBRE` VARCHAR(50) NULL,
	`PRIMER_APELLIDO` VARCHAR(50) NULL,
	`SEGUNDO_APELLIDO` VARCHAR(50) NULL,
	`CURP` VARCHAR(50) NULL,
    `EDAD`INT NOT NULL, 
	CONSTRAINT `PK_MH_PERSONA` PRIMARY KEY (`ID_PERSONA` ASC)
)
COMMENT = 'Registro de personas, puede tener o no un rol dentro de la aplicacion'

;

CREATE TABLE `MH_ROL`
(
	`ID_ROL` SMALLINT NOT NULL,
	`DESCRIPCION` VARCHAR(50) NULL,
	CONSTRAINT `PK_ID_ROL` PRIMARY KEY (`ID_ROL` ASC)
)
COMMENT = 'Tabla que guarda la lista de Roles para el sistema'

;

CREATE TABLE `MH_ROL_MENU`
(
	`ID_ROL` SMALLINT NOT NULL,
	`ID_MENU` SMALLINT NOT NULL,
	CONSTRAINT `PK_MH_ROL_MENU` PRIMARY KEY (`ID_ROL` ASC, `ID_MENU` ASC)
)
COMMENT = 'Tlabla que relaciona los menús con los roles.'

;

CREATE TABLE `MH_SINTOMAS`
(
	`FECHA` DATE NOT NULL,
	`ID_PACIENTE` BIGINT NOT NULL,
	`TOS` BOOL NULL,
	`CEFALEA` BOOL NULL,
	`DOLOR_ABDOMINAL` BOOL NULL,
	`DOLOR_TORACICO` BOOL NULL,
	`VOMITO` BOOL NULL,
	`IRRITABLE` BOOL NULL,
	`PERDIDA_OLFATO_GUSTO` BOOL NULL,
	`DIARREA` BOOL NULL,
	`ODINOFAGIA` BOOL NULL,
	`RINORREA` BOOL NULL,
	`MIALGIAS` BOOL NULL,
	CONSTRAINT `PK_MH_SINTOMAS` PRIMARY KEY (`FECHA` ASC, `ID_PACIENTE` ASC)
)

;

CREATE TABLE `MH_USUARIO`
(
	`ID_USUARIO` VARCHAR(20) NOT NULL,
	`CONTRASENIA` VARCHAR(50) NULL,
	`ACTIVO` BOOL NULL,
	`ID_PERSONA` INT NULL,
    `EMAIL` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_MH_USUARIO` PRIMARY KEY (`ID_USUARIO` ASC)
)
COMMENT = 'Tabla para almacenar los usuarios que tienen acceso al sistema, un usuario podría tener más de un rol.'

;

CREATE TABLE `MH_USUARIO_ROL`
(
	`ID_USUARIO` VARCHAR(50) NOT NULL,
	`ID_ROL` SMALLINT NOT NULL,
	CONSTRAINT `PK_MH_USUARIO_ROL` PRIMARY KEY (`ID_USUARIO` ASC, `ID_ROL` ASC)
)

;

CREATE TABLE `MH_VALORES_REFERENCIA`
(
	`SAT_OXIGENO_NORMAL_MIN` FLOAT(5,2) NOT NULL DEFAULT 92.0,
    `SAT_OXIGENO_NORMAL_MAX` FLOAT(5,2) NOT NULL DEFAULT 100.0, 
	`SAT_OXIGENO_WARNING_MIN` FLOAT(5,2) NOT NULL DEFAULT 81.0,
    `SAT_OXIGENO_WARNING_MAX` FLOAT(5,2) NOT NULL DEFAULT 92.0,
    `SAT_OXIGENO_ALERT_MIN` FLOAT(5,2) NOT NULL DEFAULT 0.0,
    `SAT_OXIGENO_ALERT_MAX` FLOAT(5,2) NOT NULL DEFAULT 81.0,
    `TEMPERATURA_NORMAL_MIN` FLOAT(4,2) NOT NULL DEFAULT 33.0,
    `TEMPERATURA_NORMAL_MAX` FLOAT(4,2) NOT NULL DEFAULT 37.0,
    `TEMPERATURA_WARNING_MIN` FLOAT(4,2) NOT NULL DEFAULT 37.0,
    `TEMPERATURA_WARNING_MAX` FLOAT(4,2) NOT NULL DEFAULT 38.0,
    `TEMPERATURA_ALERT_MIN` FLOAT(4,2) NOT NULL DEFAULT 38.0,
    `TEMPERATURA_ALERT_MAX` FLOAT(4,2) NOT NULL DEFAULT 50.0,
    `CAPNOGRAFIA_NORMAL_MIN` SMALLINT NOT NULL DEFAULT 35,
    `CAPNOGRAFIA_NORMAL_MAX` SMALLINT NOT NULL DEFAULT 37,
	`CAPNOGRAFIA_WARNING_MIN` SMALLINT NOT NULL DEFAULT 40,
    `CAPNOGRAFIA_WARNING_MAX` SMALLINT NOT NULL DEFAULT 45,
    `CAPNOGRAFIA_ALERT_MIN` SMALLINT NOT NULL DEFAULT 45,
    `CAPNOGRAFIA_ALERT_MAX` SMALLINT NOT NULL DEFAULT 45,
    `FREC_CARDIACA_NORMAL_MIN` SMALLINT NOT NULL DEFAULT 60,
    `FREC_CARDIACA_NORMAL_MAX` SMALLINT NOT NULL DEFAULT 80,
	`FREC_CARDIACA_WARNING_MIN` SMALLINT NOT NULL DEFAULT 81,
    `FREC_CARDIACA_WARNING_MAX` SMALLINT NOT NULL DEFAULT 99,
    `FREC_CARDIACA_ALERT_MIN` SMALLINT NOT NULL DEFAULT 100,
	`FREC_CARDIACA_ALERT_MAX` SMALLINT NOT NULL DEFAULT 130,
    `FREC_RESPIRATORIA_NORMAL_MIN` SMALLINT NOT NULL DEFAULT 16,
	`FREC_RESPIRATORIA_NORMAL_MAX` SMALLINT NOT NULL DEFAULT 18,
    `FREC_RESPIRATORIA_WARNING_MIN` SMALLINT NOT NULL DEFAULT 19,
	`FREC_RESPIRATORIA_WARNING_MAX` SMALLINT NOT NULL DEFAULT 20,
    `FREC_RESPIRATORIA_ALERT_MIN` SMALLINT NOT NULL DEFAULT 21,
	`FREC_RESPIRATORIA_ALERT_MAX` SMALLINT NOT NULL DEFAULT 30,
    `ID_VALREF` SMALLINT NOT NULL,
    `PRE_ART_SISTOLICA_NORMAL_MIN` INT NOT NULL DEFAULT 100,
	`PRE_ART_SISTOLICA_NORMAL_MAX` INT NOT NULL DEFAULT 120,
    `PRE_ART_SISTOLICA_WARNING_MIN` INT NOT NULL DEFAULT 121,
    `PRE_ART_SISTOLICA_WARNING_MAX`  INT NOT NULL DEFAULT 139,
	`PRE_ART_SISTOLICA_ALERT_MIN` INT NOT NULL DEFAULT 140,
    `PRE_ART_SISTOLICA_ALERT_MAX` INT NOT NULL DEFAULT 190,
    `PRE_ART_DIASTOLICA_NORMAL_MIN` INT NOT NULL DEFAULT 60,
	`PRE_ART_DIASTOLICA_NORMAL_MAX` INT NOT NULL DEFAULT 80,
    `PRE_ART_DIASTOLICA_WARNING_MIN` INT NOT NULL DEFAULT 81,
    `PRE_ART_DIASTOLICA_WARNING_MAX`  INT NOT NULL DEFAULT 89,
	`PRE_ART_DIASTOLICA_ALERT_MIN` INT NOT NULL DEFAULT 90,
    `PRE_ART_DIASTOLICA_ALERT_MAX` INT NOT NULL DEFAULT 100,
	CONSTRAINT `PK_MH_VALORES_REFERENCIA` PRIMARY KEY (`ID_VALREF` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `MH_ANTECEDENTES` 
 ADD INDEX `IXFK_MH_ANTECEDENTES_MH_PACIENTE` (`ID_PACIENTE` ASC)
;

ALTER TABLE `MH_BITACORA` 
 ADD INDEX `IXFK_MH_BITACORA_MH_EVENTOBITACORA` (`ID_EVENTO` ASC)
;

ALTER TABLE `MH_BITACORA` 
 ADD INDEX `IXFK_MH_BITACORA_MH_USUARIO` (`ID_USUARIO` ASC)
;

ALTER TABLE `MH_CARETA_HOSPITAL` 
 ADD INDEX `IXFK_MH_CARETA_HOSPITAL_MH_CARETA` (`ID_CARETA` ASC)
;

ALTER TABLE `MH_CARETA_HOSPITAL` 
 ADD INDEX `IXFK_MH_CARETA_HOSPITAL_MH_HOSPITAL` (`ID_HOSPITAL` ASC)
;

ALTER TABLE `MH_HOSPITAL_MEDICO` 
 ADD INDEX `IXFK_MH_HOSPITAL_MEDICO_MH_HOSPITAL` (`ID_HOSPITAL` ASC)
;

ALTER TABLE `MH_HOSPITAL_MEDICO` 
 ADD INDEX `IXFK_MH_HOSPITAL_MEDICO_MH_MEDICO` (`ID_MEDICO` ASC)
;

ALTER TABLE `MH_MEDICO` 
 ADD INDEX `IXFK_MEDICO_HOSPITAL` (`ID_MEDICO` ASC)
;

ALTER TABLE `MH_MEDICO` 
 ADD INDEX `IXFK_MEDICO_MH_PERSONA` (`ID_PERSONA` ASC)
;

ALTER TABLE `MH_MEDIDAS` 
 ADD INDEX `IXFK_MH_MEDIDAS_MH_CARETA` (`ID_CARETA` ASC)
;

ALTER TABLE `MH_MEDIDAS` 
 ADD INDEX `IXFK_MH_MEDIDAS_MH_PACIENTE` (`ID_PACIENTE` ASC)
;

ALTER TABLE `MH_MENU_OPCION` 
 ADD INDEX `IXFK_MH_MENU_OPCION_MH_MENU` (`ID_MENU` ASC)
;

ALTER TABLE `MH_MENU_OPCION` 
 ADD INDEX `IXFK_MH_MENU_OPCION_MH_MENU_02` (`ID_SUB_MENU` ASC)
;

ALTER TABLE `MH_MENU_OPCION` 
 ADD INDEX `IXFK_MH_MENU_OPCION_MH_OPCION` (`ID_OPCION` ASC)
;

ALTER TABLE `MH_PACIENTE` 
 ADD INDEX `IXFK_MH_PACIENTE_MH_CARETA` (`ID_CARETA` ASC)
;

ALTER TABLE `MH_PACIENTE` 
 ADD INDEX `IXFK_MH_PACIENTE_MH_ESTADOPACIENTE` (`ID_ESTADOPACIENTE` ASC)
;

ALTER TABLE `MH_PACIENTE` 
 ADD INDEX `IXFK_PACIENTE_HOSPITAL` (`ID_HOSPITAL` ASC)
;

ALTER TABLE `MH_PACIENTE` 
 ADD INDEX `IXFK_PACIENTE_MH_PERSONA` (`ID_PERSONA` ASC)
;

ALTER TABLE `MH_PACIENTE_MEDICO` 
 ADD INDEX `IXFK_MH_PACIENTE_MEDICO_MH_MEDICO` (`ID_MEDICO` ASC)
;

ALTER TABLE `MH_PACIENTE_MEDICO` 
 ADD INDEX `IXFK_MH_PACIENTE_MEDICO_MH_PACIENTE` (`ID_PACIENTE` ASC)
;

ALTER TABLE `MH_PERSONA` 
 ADD INDEX `IXFK_MH_PERSONA_MH_GENERO` (`ID_GENERO` ASC)
;

ALTER TABLE `MH_ROL_MENU` 
 ADD INDEX `IXFK_MH_ROL_MENU_MH_MENU` (`ID_MENU` ASC)
;

ALTER TABLE `MH_ROL_MENU` 
 ADD INDEX `IXFK_MH_ROL_MENU_MH_ROL` (`ID_ROL` ASC)
;

ALTER TABLE `MH_SINTOMAS` 
 ADD INDEX `IXFK_MH_SINTOMAS_MH_PACIENTE` (`ID_PACIENTE` ASC)
;

ALTER TABLE `MH_USUARIO` 
 ADD INDEX `IXFK_MH_USUARIO_MH_PERSONA` (`ID_PERSONA` ASC)
;

ALTER TABLE `MH_USUARIO` 
 ADD INDEX `IXID_USUARIO` (`ID_USUARIO` ASC)
;

ALTER TABLE `MH_USUARIO_ROL` 
 ADD INDEX `IXFK_MH_USUARIO_ROL_MH_ROL` (`ID_ROL` ASC)
;

ALTER TABLE `MH_USUARIO_ROL` 
 ADD INDEX `IXFK_MH_USUARIO_ROL_MH_USUARIO` (`ID_USUARIO` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `MH_ANTECEDENTES` 
 ADD CONSTRAINT `FK_MH_ANTECEDENTES_MH_PACIENTE`
	FOREIGN KEY (`ID_PACIENTE`) REFERENCES `MH_PACIENTE` (`ID_PACIENTE`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_BITACORA` 
 ADD CONSTRAINT `FK_MH_BITACORA_MH_EVENTOBITACORA`
	FOREIGN KEY (`ID_EVENTO`) REFERENCES `MH_EVENTOBITACORA` (`ID_EVENTO`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_BITACORA` 
 ADD CONSTRAINT `FK_MH_BITACORA_MH_USUARIO`
	FOREIGN KEY (`ID_USUARIO`) REFERENCES `MH_USUARIO` (`ID_USUARIO`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_CARETA_HOSPITAL` 
 ADD CONSTRAINT `FK_MH_CARETA_HOSPITAL_MH_CARETA`
	FOREIGN KEY (`ID_CARETA`) REFERENCES `MH_CARETA` (`ID_CARETA`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_CARETA_HOSPITAL` 
 ADD CONSTRAINT `FK_MH_CARETA_HOSPITAL_MH_HOSPITAL`
	FOREIGN KEY (`ID_HOSPITAL`) REFERENCES `MH_HOSPITAL` (`ID_HOSPITAL`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_HOSPITAL_MEDICO` 
 ADD CONSTRAINT `FK_MH_HOSPITAL_MEDICO_MH_HOSPITAL`
	FOREIGN KEY (`ID_HOSPITAL`) REFERENCES `MH_HOSPITAL` (`ID_HOSPITAL`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_HOSPITAL_MEDICO` 
 ADD CONSTRAINT `FK_MH_HOSPITAL_MEDICO_MH_MEDICO`
	FOREIGN KEY (`ID_MEDICO`) REFERENCES `MH_MEDICO` (`ID_MEDICO`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_MEDICO` 
 ADD CONSTRAINT `FK_MEDICO_MH_PERSONA`
	FOREIGN KEY (`ID_PERSONA`) REFERENCES `MH_PERSONA` (`ID_PERSONA`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_MEDIDAS` 
 ADD CONSTRAINT `FK_MH_MEDIDAS_MH_CARETA`
	FOREIGN KEY (`ID_CARETA`) REFERENCES `MH_CARETA` (`ID_CARETA`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_MEDIDAS` 
 ADD CONSTRAINT `FK_MH_MEDIDAS_MH_PACIENTE`
	FOREIGN KEY (`ID_PACIENTE`) REFERENCES `MH_PACIENTE` (`ID_PACIENTE`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_MENU_OPCION` 
 ADD CONSTRAINT `FK_MH_MENU_OPCION_MH_MENU`
	FOREIGN KEY (`ID_MENU`) REFERENCES `MH_MENU` (`ID_MENU`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_MENU_OPCION` 
 ADD CONSTRAINT `FK_MH_MENU_OPCION_MH_OPCION`
	FOREIGN KEY (`ID_OPCION`) REFERENCES `MH_OPCION` (`ID_OPCION`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_MENU_OPCION` 
 ADD CONSTRAINT `FK_MH_MENU_OPCION_MH_SUBMENU`
	FOREIGN KEY (`ID_SUB_MENU`) REFERENCES `MH_MENU` (`ID_MENU`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_PACIENTE` 
 ADD CONSTRAINT `FK_MH_PACIENTE_MH_CARETA`
	FOREIGN KEY (`ID_CARETA`) REFERENCES `MH_CARETA` (`ID_CARETA`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_PACIENTE` 
 ADD CONSTRAINT `FK_MH_PACIENTE_MH_ESTADOPACIENTE`
	FOREIGN KEY (`ID_ESTADOPACIENTE`) REFERENCES `MH_ESTADOPACIENTE` (`ID_ESTADOPACIENTE`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_PACIENTE` 
 ADD CONSTRAINT `FK_PACIENTE_HOSPITAL`
	FOREIGN KEY (`ID_HOSPITAL`) REFERENCES `MH_HOSPITAL` (`ID_HOSPITAL`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_PACIENTE` 
 ADD CONSTRAINT `FK_PACIENTE_MH_PERSONA`
	FOREIGN KEY (`ID_PERSONA`) REFERENCES `MH_PERSONA` (`ID_PERSONA`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_PACIENTE_MEDICO` 
 ADD CONSTRAINT `FK_MH_PACIENTE_MEDICO_MH_MEDICO`
	FOREIGN KEY (`ID_MEDICO`) REFERENCES `MH_MEDICO` (`ID_MEDICO`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_PACIENTE_MEDICO` 
 ADD CONSTRAINT `FK_MH_PACIENTE_MEDICO_MH_PACIENTE`
	FOREIGN KEY (`ID_PACIENTE`) REFERENCES `MH_PACIENTE` (`ID_PACIENTE`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_PERSONA` 
 ADD CONSTRAINT `FK_M_PERSONA_MH_GENERO`
	FOREIGN KEY (`ID_GENERO`) REFERENCES `MH_GENERO` (`ID_GENERO`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_ROL_MENU` 
 ADD CONSTRAINT `FK_MH_ROL_MENU_RM_MENU`
	FOREIGN KEY (`ID_MENU`) REFERENCES `MH_MENU` (`ID_MENU`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_ROL_MENU` 
 ADD CONSTRAINT `FK_MH_ROL_MENU_RM_ROL`
	FOREIGN KEY (`ID_ROL`) REFERENCES `MH_ROL` (`ID_ROL`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_SINTOMAS` 
 ADD CONSTRAINT `FK_MH_SINTOMAS_MH_PACIENTE`
	FOREIGN KEY (`ID_PACIENTE`) REFERENCES `MH_PACIENTE` (`ID_PACIENTE`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_USUARIO` 
 ADD CONSTRAINT `FK_MH_USUARIO_MH_PERSONA`
	FOREIGN KEY (`ID_PERSONA`) REFERENCES `MH_PERSONA` (`ID_PERSONA`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_USUARIO_ROL` 
 ADD CONSTRAINT `FK_MH_USUARIO_ROL_MH_ROL`
	FOREIGN KEY (`ID_ROL`) REFERENCES `MH_ROL` (`ID_ROL`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MH_USUARIO_ROL` 
 ADD CONSTRAINT `FK_MH_USUARIO_ROL_MH_USUARIO`
	FOREIGN KEY (`ID_USUARIO`) REFERENCES `MH_USUARIO` (`ID_USUARIO`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
COMMIT;